name: gym_quest
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.5
  http: ^1.2.0
  path: ^1.9.1  
  file_picker: ^8.0.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/latpulldown.jpg
    - assets/images/dumbbell_rack.jpg
    - assets/images/variable-machine.png
    - assets/images/lap_pools.png
    - assets/images/calesthenics.jpg
    - assets/images/branding/summit.png
    - assets/gifs/Chest-supported_row_GIF.gif
    - assets/gifs/seated-cable-row.gif
    - assets/images/bench-press.png
    - assets/images/compass.png